# sampling params
sampling:
  # type
  type: antipodal_depth
  gripper_width: 0.05
  # antipodality
  friction_coef: 0.15
  depth_grad_thresh: 0.003
  depth_grad_gaussian_sigma: 1.0
  downsample_rate: 2
  max_rejection_samples: 100000

  # distance
  max_dist_from_center: 1000
  min_dist_from_boundary: 45
  min_grasp_dist: 10.0
  angle_dist_weight: 5.0

  # depth sampling
  depth_sampling_mode: uniform
  depth_samples_per_grasp: 1
  depth_sample_win_height: 1
  depth_sample_win_width: 1
  min_depth_offset: 0.015
  max_depth_offset: 0.05
metrics:
  force_closure:
    quality_method: force_closure
    friction_coef: 0.5
    num_cone_faces: 8
    soft_fingers: 1
    quality_type: quasi_static
    all_contacts_required: 1
    check_approach: Flase
    num_quality_samples: 50
    # optional deterministic parameters
    torque_scaling: 0.01
    wrench_norm_thresh: 0.001
    wrench_regularizer: 0.0000000001
